# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 08:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retest', '0005_auto_20170206_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semester',
            old_name='year',
            new_name='batch',
        ),
    ]
