# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 08:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retest', '0006_auto_20170227_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='batch',
        ),
    ]
