# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retest', '0009_auto_20170318_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='retest',
            name='Student',
        ),
        migrations.RemoveField(
            model_name='retest',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='retest',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='student',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='dept',
        ),
        migrations.DeleteModel(
            name='Retest',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
