# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retest', '0010_auto_20170318_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(max_length=50)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retest.Departement')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retest.Semester')),
            ],
        ),
    ]
