# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 08:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retest', '0012_auto_20170318_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='year',
        ),
    ]
