# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 10:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retest', '0013_remove_semester_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retest',
            name='Student',
        ),
        migrations.RemoveField(
            model_name='retest',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='retest',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='retest',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='student',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sem',
        ),
        migrations.DeleteModel(
            name='Retest',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
