# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retest', '0014_auto_20170318_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('admnno', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('batch', models.CharField(max_length=1)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retest.Departement')),
                ('sem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retest.Semester')),
            ],
        ),
    ]
