# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retest', '0016_retest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('div', models.CharField(max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='retest',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retest.Batch'),
        ),
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retest.Batch'),
        ),
    ]
