# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retest', '0018_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='retest',
            name='hod',
            field=models.BooleanField(default=False),
        ),
    ]
