# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 22:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('retest', '0020_auto_20170325_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True, default='')),
                ('bio', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('organization', models.CharField(blank=True, default='', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='accepted',
            name='admnno',
        ),
        migrations.RemoveField(
            model_name='accepted',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='accepted',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='accepted',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='accepted',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='student',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='student',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sem',
        ),
        migrations.AlterField(
            model_name='retest',
            name='admnno',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Accepted',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
