# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retest', '0021_auto_20170326_0354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('admnno', models.CharField(max_length=50)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retest.Batch')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retest.Departement')),
                ('sem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retest.Semester')),
            ],
        ),
    ]
