# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retest', '0022_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=('main.UserProfile.photo', 'profiles'), verbose_name='Profile Picture'),
        ),
    ]
