# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retest', '0033_auto_20170327_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retest.Departement'),
        ),
    ]
