# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retest', '0034_auto_20170327_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='batch',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
