# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retest', '0037_auto_20170328_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retest.Departement'),
        ),
    ]
