# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retest', '0042_auto_20170328_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='retest',
            name='is_principal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='/'),
        ),
    ]
