# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retest', '0045_auto_20170430_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectors',
            name='unavailable',
            field=models.BooleanField(default=False),
        ),
    ]
