# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retest', '0046_projectors_unavailable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectors',
            name='unavailable',
            field=models.BooleanField(default=True),
        ),
    ]
