# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 06:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retest', '0047_auto_20170430_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectors',
            old_name='unavailable',
            new_name='available',
        ),
    ]
