# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 07:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retest', '0048_auto_20170430_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventgraphicshall',
            old_name='fromt',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='eventgraphicshall',
            old_name='to',
            new_name='start',
        ),
    ]
