# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retest', '0052_auto_20170430_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoriums',
            name='sec',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='retest.Section'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='sec',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='retest.Section'),
        ),
        migrations.AddField(
            model_name='extension_cables',
            name='sec',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='retest.Section'),
        ),
        migrations.AddField(
            model_name='graphicshalls',
            name='sec',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='retest.Section'),
        ),
        migrations.AddField(
            model_name='labs',
            name='sec',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='retest.Section'),
        ),
        migrations.AddField(
            model_name='mikesystems',
            name='sec',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='retest.Section'),
        ),
        migrations.AddField(
            model_name='projectors',
            name='sec',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='retest.Section'),
        ),
    ]
