# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retest', '0053_auto_20170430_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='retest',
            name='is_sure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='retest',
            name='notify',
            field=models.BooleanField(default=False),
        ),
    ]
