# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retest', '0055_auto_20170501_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='dept',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='retest.Departement'),
        ),
    ]
