# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 10:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retest', '0056_auto_20170501_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dept',
        ),
    ]
