# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 10:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retest', '0057_remove_profile_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dept',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='retest.Departement'),
        ),
    ]
