# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retest', '0059_auto_20170501_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allusers',
            name='avatar',
            field=models.ImageField(upload_to='retest/static/images/'),
        ),
    ]
