# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retest', '0060_auto_20170501_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='rep',
            name='semester',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='retest.Semester'),
        ),
        migrations.AlterField(
            model_name='rep',
            name='batch',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='retest.Batch'),
        ),
    ]
