# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retest', '0061_auto_20170501_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='student',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sem',
        ),
        migrations.AddField(
            model_name='rep',
            name='is_true',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
