# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 18:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retest', '0062_auto_20170501_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rep',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bar', to=settings.AUTH_USER_MODEL),
        ),
    ]
