# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retest', '0064_auto_20170501_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='retest',
            name='uniquecode',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='retest.Rep'),
        ),
    ]
