# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retest', '0065_retest_uniquecode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rep',
            name='is_true',
        ),
        migrations.RemoveField(
            model_name='retest',
            name='uniquecode',
        ),
        migrations.AlterField(
            model_name='retest',
            name='date',
            field=models.DateField(),
        ),
    ]
