# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retest', '0066_auto_20170502_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retest',
            name='date',
            field=models.DateField(default=0),
        ),
    ]
