# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-05 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retest', '0068_projectors_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='retest',
            name='is_rep',
            field=models.BooleanField(default=False),
        ),
    ]
