# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retest', '0070_auto_20170505_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoriums',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='extension_cables',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='graphicshalls',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='labs',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mikesystems',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='retest',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
