# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 07:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retest', '0071_auto_20170507_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='sec',
        ),
    ]
