# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-08 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retest', '0072_remove_classroom_sec'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventgraphicshall',
            old_name='is_ashok',
            new_name='is_accept',
        ),
        migrations.RenameField(
            model_name='eventgraphicshall',
            old_name='is_principal',
            new_name='is_head',
        ),
        migrations.RemoveField(
            model_name='retest',
            name='is_rep',
        ),
        migrations.AddField(
            model_name='eventauditorium',
            name='is_head',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventauditorium',
            name='is_incharge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventclassroom',
            name='is_head',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventclassroom',
            name='is_incharge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventextensioncable',
            name='is_head',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventextensioncable',
            name='is_incharge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventlab',
            name='is_head',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventlab',
            name='is_incharge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventmikesystem',
            name='is_head',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventmikesystem',
            name='is_incharge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventprojector',
            name='is_head',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventprojector',
            name='is_incharge',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eventauditorium',
            name='is_accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eventclassroom',
            name='is_accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eventextensioncable',
            name='is_accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eventlab',
            name='is_accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eventmikesystem',
            name='is_accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eventprojector',
            name='is_accept',
            field=models.BooleanField(default=False),
        ),
    ]
