# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-08 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retest', '0074_remove_eventclassroom_is_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventextensioncable',
            name='recieved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventmikesystem',
            name='recieved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventprojector',
            name='recieved',
            field=models.BooleanField(default=False),
        ),
    ]
